from random import randint

titles = [
    "It's logging time!",
    "To log or not to log, that is the question",
    "Ho sonno...",
    "If a logging log logger is logging logs, how many logs does a logging logger log?",
    "Log on... log off... log on... log off...",
    "Are you working too much?",
    "A logger is never too late, nor never too early, it arrives exactly when it is needed",
    "I don't think so",
    "Ambrogio, dove sono i miei pancakes?",
    "Ho freddo...",
    "What is the meaning of all this?",
    "Are you cool enough to log?",
    "I have the eyes of a hawk, and the ears of a fox",
    "Lickitty split",
    "Che caldo Ferdando",
    "Po po po po po po po po po po",
    "One does not simply log into Mordor",
    "This is a funny joke",
    "Made with splitting edge technology",
    "Blazingly fast",
    "Logging like your life depends on it",
    "I could have been baking biscuits instead",
    "What's for dinner tonight?",
    "Are you sure you can trust me?",
    "Writing logs since 1974",
    "Un ragazzo della terza età",
    "I could do with some chocolate right now",
    "Always log responsibly",
    "Who do you think you are, logging so recklessly?",
    "Compatible with...who knows?",
    "Just wait until you see the pivot table",
    "And a good day to you too",
    "Into the danger zone",
    "Croccante!",
    "I'm afraid I can't let you do that",
    "Nobody puts Logger in a corner",
    "Proudly sponsored by absolutely nobody",
    "It's a wonderful world",
    "With all the hope in my heart, and all the doubt in my mind",
    "The best log of your life",
    "All roads lead to Logger",
    "Don't look behind you",
    "Go for a walk every now and again",
    "Are you sure you haven't forgotten anything?",
    "Well well well, look what the cat dragged in today",
    "Always prepared",
    "Time spent on the phone doesn't count",
    "Break time!",
    "Look outside if your bike is still there",
    "What's the matter, getting tired?",
    "You'll have the time of your life",
    "Fotooooooo!!!! :-) :-D :-) :-D",
    "Fa caldo...",
    "I have the power!",
    "It is time for more... experiments...",
    "The same thing I try to do every night: try to take over the world!",
    "Stay hydrated",
    "Your bank account has been successfuly updated",
    "Remember to recharge your laptop",
    "Questo non è Ibiza",
    "Forse si, forse no",
    "Time for a cuppa",
    "Mi scappa la pippa, mi scappa la pippi, mi scappa la pippi papa",
    "The previous version was better",
    "I'm a logger and I'm OK. I sleep all night and I work all day",
    "Only 5€ per minute!",
    "Facciamo un PanQuiz!",
    "Will it rain tomorrow?",
    "No animals were harmed in creating Logger",
    "Write it on a post-it",
    "How are you feeling today?",
    "You'd be earning more in Sweden",
    "Dove si balla!",
    "You have 99+ new messages",
    "Nuda, tutta la notte...",
    "Service with a smile",
    "Ci vediamo al party!",
    "Dobbiamo fissare un chat",
    "What is a Logger? A miserable little pile of secrets!",
    "You're the Logger? Well I didn't vote for you...",
    "This Logger is pining for the fjords!",
    "Whatever you do, don't mention the war!",
    "Ancora non ho visto il mare",
    "What do you think you're doing with that spunge?",
    "Mi sto faccendo il culo a tarallo",
    "A bestia!",
    "Ho chuiso il cancello, possiamo andare a letto",
    "Squeaky wheel gets the kick!",
    "A logging Logger gathers no moss",
    "He is the Logger we need, not the Logger we deserve",
    "100% Made in Italy",
    "Award winning software"

    

]

def random_title():
 
    random_num = randint(0, len(titles) - 1)
    return titles[random_num]